=== imp14a/lab_fisica/Service/resources/LaboratorioFisica.xsd
<!-- Descriptor para validar los archivos XML del usuario -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="LaboratorioFisica">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="WorldProperties" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Propertie" minOccurs="4" maxOccurs="4" >
							<xs:complexType>
								<xs:attribute name="name" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:whiteSpace value="collapse"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="value" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:whiteSpace value="collapse"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="description" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:whiteSpace value="collapse"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="WorldElements" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="WorldElement" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Propertie" minOccurs="0" maxOccurs="unbounded" >
										<xs:complexType>
											<xs:attribute name="name" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:minLength value="1"/>
														<xs:whiteSpace value="collapse"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="value" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:minLength value="1"/>
														<xs:whiteSpace value="collapse"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="description" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:minLength value="1"/>
														<xs:whiteSpace value="collapse"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="name" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:whiteSpace value="collapse"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ActivityInfo" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Field" minOccurs="3" maxOccurs="3">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Content" type="xs:string"  minOccurs="1" maxOccurs="1"/>
								</xs:sequence>
								<xs:attribute name="name" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1"/>
											<xs:whiteSpace value="collapse"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- 
	Este tipo deberia ser generico
<xs:complexType name="t_Propertie">
    <xs:attribute name="name" use="required">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
                <xs:whiteSpace value="collapse"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="value" use="required">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
                <xs:whiteSpace value="collapse"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="description" use="required">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
                <xs:whiteSpace value="collapse"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
</xs:complexType>
-->

</xs:schema>

=== imp14a/lab_fisica/Service/resources/Pendulo_sample.xml
<?xml version="1.0" encoding="UTF-8"?>

<LaboratorioFisica
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='http://lab_fisica/Service/Resources/LaboratorioFisica.xsd'>
    <WorldProperties>
        <Propertie name="gravity" value="9.82" description="Gravedad del ambiente"></Propertie>
        <Propertie name="density" value="2.00" description="Densidad del ambiente"></Propertie>
        <Propertie name="showAxes" value="false" description="Inidica si se mostraran los ejes"></Propertie>
        <Propertie name="showGround" value="false" description="Inidica si se mostrara el suelo"></Propertie>
    </WorldProperties>
    <WorldElements>
        <WorldElement name="sphere">
            <Propertie name="position" value="2,2" description="Ubicación de de la esfera en el ejecordenado, valores separados por coma"></Propertie>
            <Propertie name="mass" value="221" description="Masa de la esfera del péndulo"></Propertie>
            <Propertie name="radio" value="213" description="Radio para definir el tamaño de la esfera"></Propertie>
            <Propertie name="elasticity" value="213" description="Elasticidad de la esfera"></Propertie>
        </WorldElement>
        <WorldElement name="pendulo">
            <Propertie name="radio" value="2.0" description="Radio de distancia hacia el péndulo"></Propertie>
            <Propertie name="angle" value="90" description="ángulo de inclinacion del péndulo en grados"></Propertie>
        </WorldElement>
    </WorldElements>
    <ActivityInfo>
        <Field name="Introducción">
            <Content></Content>
        </Field>
        <Field name="Procedimiento">
            <Content></Content>
        </Field>
        <Field name="Concluciones">
            <Content></Content>
        </Field>
    </ActivityInfo>
</LaboratorioFisica>
